# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMstep <- function(Y, alpha, beta, theta, max_cat, constraint, a0, A0, b0, B0, maxit, tol, verbose, std) {
    .Call(`_pgIRT_EMstep`, Y, alpha, beta, theta, max_cat, constraint, a0, A0, b0, B0, maxit, tol, verbose, std)
}

dyn_EMstep <- function(Y, alpha, beta, theta, max_cat, constraint, a0, A0, b0, B0, theta0, Delta0, Delta, session_individual, bill_session, matched_bill, maxit, tol, verbose, std) {
    .Call(`_pgIRT_dyn_EMstep`, Y, alpha, beta, theta, max_cat, constraint, a0, A0, b0, B0, theta0, Delta0, Delta, session_individual, bill_session, matched_bill, maxit, tol, verbose, std)
}

prediction <- function(alpha, beta, theta, max_cat, bill_session, model, type) {
    .Call(`_pgIRT_prediction`, alpha, beta, theta, max_cat, bill_session, model, type)
}

