# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Calc_predY_bin <- function(theta, alpha, beta) {
    .Call(`_pgIRT_Calc_predY_bin`, theta, alpha, beta)
}

Calc_predY_bin_dyn <- function(theta, alpha, beta, bill_session) {
    .Call(`_pgIRT_Calc_predY_bin_dyn`, theta, alpha, beta, bill_session)
}

Calc_predY_mlt <- function(theta, alpha, beta) {
    .Call(`_pgIRT_Calc_predY_mlt`, theta, alpha, beta)
}

Calc_predY_mlt_dyn <- function(theta, alpha, beta, bill_session) {
    .Call(`_pgIRT_Calc_predY_mlt_dyn`, theta, alpha, beta, bill_session)
}

get_Eomega_bin <- function(theta, alpha, beta) {
    .Call(`_pgIRT_get_Eomega_bin`, theta, alpha, beta)
}

get_Eomega_bin_dyn <- function(theta, alpha, beta, bill_session) {
    .Call(`_pgIRT_get_Eomega_bin_dyn`, theta, alpha, beta, bill_session)
}

get_Eomega_mlt <- function(theta, alpha, beta) {
    .Call(`_pgIRT_get_Eomega_mlt`, theta, alpha, beta)
}

get_Eomega_mlt_dyn <- function(theta, alpha, beta, bill_session) {
    .Call(`_pgIRT_get_Eomega_mlt_dyn`, theta, alpha, beta, bill_session)
}

organize_Y <- function(Y1, Y2, Y3) {
    .Call(`_pgIRT_organize_Y`, Y1, Y2, Y3)
}

update_alpha_bin <- function(Y, omega, beta, theta, a0, A0) {
    .Call(`_pgIRT_update_alpha_bin`, Y, omega, beta, theta, a0, A0)
}

update_alpha_bin_dyn <- function(Y, omega, beta, theta, a0, A0, bill_session, matched_bill) {
    .Call(`_pgIRT_update_alpha_bin_dyn`, Y, omega, beta, theta, a0, A0, bill_session, matched_bill)
}

update_alpha_mlt <- function(Y1, Y2, Omega, beta, theta, a0, A0) {
    .Call(`_pgIRT_update_alpha_mlt`, Y1, Y2, Omega, beta, theta, a0, A0)
}

update_alpha_mlt_dyn <- function(Y1, Y2, Omega, beta, theta, a0, A0, bill_session, matched_bill) {
    .Call(`_pgIRT_update_alpha_mlt_dyn`, Y1, Y2, Omega, beta, theta, a0, A0, bill_session, matched_bill)
}

update_beta_bin <- function(Y, omega, alpha, theta, b0, B0) {
    .Call(`_pgIRT_update_beta_bin`, Y, omega, alpha, theta, b0, B0)
}

update_beta_bin_dyn <- function(Y, omega, alpha, theta, b0, B0, bill_session) {
    .Call(`_pgIRT_update_beta_bin_dyn`, Y, omega, alpha, theta, b0, B0, bill_session)
}

update_beta_mlt <- function(Y1, Y2, Omega, alpha, theta, b0, B0) {
    .Call(`_pgIRT_update_beta_mlt`, Y1, Y2, Omega, alpha, theta, b0, B0)
}

update_beta_mlt_dyn <- function(Y1, Y2, Omega, alpha, theta, b0, B0, bill_session) {
    .Call(`_pgIRT_update_beta_mlt_dyn`, Y1, Y2, Omega, alpha, theta, b0, B0, bill_session)
}

update_theta_bin <- function(Y, omega, alpha, beta, constraint, is_const) {
    .Call(`_pgIRT_update_theta_bin`, Y, omega, alpha, beta, constraint, is_const)
}

update_theta_bin_dyn <- function(Y, omega, alpha, beta, theta0, Delta0, Delta, constraint, is_const, session_individual, bill_session) {
    .Call(`_pgIRT_update_theta_bin_dyn`, Y, omega, alpha, beta, theta0, Delta0, Delta, constraint, is_const, session_individual, bill_session)
}

update_theta_mlt <- function(Y1, Y2, Omega, alpha, beta, constraint, is_const, max_cat, num_cat) {
    .Call(`_pgIRT_update_theta_mlt`, Y1, Y2, Omega, alpha, beta, constraint, is_const, max_cat, num_cat)
}

update_theta_mlt_dyn <- function(Y1, Y2, Omega, alpha, beta, theta0, Delta0, Delta, constraint, is_const, session_individual, bill_session, max_cat, num_cat) {
    .Call(`_pgIRT_update_theta_mlt_dyn`, Y1, Y2, Omega, alpha, beta, theta0, Delta0, Delta, constraint, is_const, session_individual, bill_session, max_cat, num_cat)
}

